image: docker:git
services:
- docker:dind

stages:
- build
# TODO: Tests!

variables:
    GITLAB_IMAGE: registry.gitlab.com/franga2000/ip-2019

build:
    stage: build
    script:
        - branch=$(git rev-parse --abbrev-ref HEAD)
        - docker build -t $GITLAB_IMAGE:$branch .
#        - [ $branch = "master" ] && docker tag $GITLAB_IMAGE:$branch $GITLAB_IMAGE:latest

        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
        - docker push $GITLAB_IMAGE:$branch
#        - [ $branch = "master" ] && docker push $GITLAB_IMAGE:latest
